### ISSUE TITLE
How to submit Wizard data?

### ISSUE THREAD

**Issue by KBasher** [formio/ngFormBuilder#192] opened 2016-11-18 10:22 UTC
The following code fire an event for Form submission and gets the form data.

`<formio form="form" submission="submission"></formio>`
`$scope.$on('formSubmission', function (err, submission) { 
                console.log(submission.data);
            }`

But it does not work for Wizard submission. 
How can I bind an callback event with wizard Submit Form button?

**Comment by KBasher** [comment] 2016-11-21 15:29
When I click on Submit Form button it send a request to the url https://api.form.io/form/undefined/submission,
The following image shows it
![server](https://cloud.githubusercontent.com/assets/10288418/20488394/0a7d6c6a-b031-11e6-8011-245e23e4ee65.jpg)

How can I change this url to my project url or fire a custom function on submission?

Please help me to fixed it.

**Comment by travist** [comment] 2016-11-22 18:16
Hello, I think I may have identified where the problem resides. It may have something to do with this code right here...

https://github.com/formio/ngFormio/blob/master/src/directives/formioWizard.js#L409

This seems to be setting the API endpoint on an empty string (which would case this to occur). We will investigate further on removing that bit of code and what effect it has on the wizard renderer.

**Comment by zackurben** [comment] 2016-11-22 21:31
@KBasher what version of `ngFormio` and `ngFormBuilder` are you using? I am unable to replicate this issue.

You can see my example codepen here: http://codepen.io/anon/pen/ENmZKQ?editors=1011

**Comment by travist** [comment] 2016-11-23 01:49
@zackurben the difference between your codepen and what @KBasher is showing is that he is using the ```form``` and ```submission``` passed directly vs. using the ```src```. From looking at the code, the ```form``` and ```submission``` are what is causing the failure here.

**Comment by zackurben** [comment] 2016-11-23 16:04
@travist @KBasher It still works as intended with the latest renderer: http://codepen.io/zackurben/pen/KNmJwE?editors=1011

**Comment by KBasher** [comment] 2016-11-24 08:06
Hi, I have made it working for my project. I have created a separate function in the form builder framework ngFormBuilder-full.js  using the current scope and  named it $scope.submitWizard. I have copied some code from the existing framework functions $scope.submit. My new function generate an object of the submitted form data and pass that data to my projects JavaScript function and process that data.
The new function is as below.

`$scope.submitWizard = function () {

            if ($scope.checkErrors()) {
                return;
            }
            // Create a sanitized submission object.
            var submissionData = { data: {} };
            if ($scope.submission._id) {
                submissionData._id = $scope.submission._id;
            }
            if ($scope.submission.data._id) {
                submissionData._id = $scope.submission.data._id;
            }

            var grabIds = function (input) {
                if (!input) {
                    return [];
                }

                if (!(input instanceof Array)) {
                    input = [input];
                }

                var final = [];
                input.forEach(function (element) {
                    if (element && element._id) {
                        final.push(element._id);
                    }
                });

                return final;
            };

            var defaultPermissions = {};
            FormioUtils.eachComponent($scope.form.components, function (component) {
                if (component.type === 'resource' && component.key && component.defaultPermission) {
                    defaultPermissions[component.key] = component.defaultPermission;
                }
                if (submissionData.data.hasOwnProperty(component.key) && (component.type === 'number')) {
                    var value = $scope.submission.data[component.key];
                    if (component.type === 'number') {
                        submissionData.data[component.key] = value ? parseFloat(value) : 0;
                    }
                    else {
                        submissionData.data[component.key] = value;
                    }
                }
            }, true);

            angular.forEach($scope.submission.data, function (value, key) {
                submissionData.data[key] = value;

                // Setup the submission access.
                var perm = defaultPermissions[key];
                if (perm) {
                    submissionData.access = submissionData.access || [];

                    // Coerce value into an array for plucking.
                    if (!(value instanceof Array)) {
                        value = [value];
                    }

                    // Try to find and update an existing permission.
                    var found = false;
                    submissionData.access.forEach(function (permission) {
                        if (permission.type === perm) {
                            found = true;
                            permission.resources = permission.resources || [];
                            permission.resources.concat(grabIds(value));
                        }
                    });

                    // Add a permission, because one was not found.
                    if (!found) {
                        submissionData.access.push({
                            type: perm,
                            resources: grabIds(value)
                        });
                    }
                }
            });
            // Strip out any angular keys.
            submissionData = angular.copy(submissionData);

            //This function is declared in my project's script.

            $rootScope.SaveWizard(submissionData);
        };`
 
And the project's declared function is 

`$rootScope.SaveWizard = function (submission) {
       console.log(submission);
  };`

And I have changed the Submit Button ng-click property to submitWizard().

**Comment by zackurben** [comment] 2017-03-29 21:59
I'm closing this issue, if you need more help, feel free to open a new issue.

**Closed by zackurben** 2017-03-29 21:59 UTC
